# Generated by Django 5.2.7 on 2025-10-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blooklist',
            fields=[
                ('blooklist_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='blooklists/images/')),
            ],
        ),
    ]
